name: dslink_webctrl
dependencies:
  dslink:
    git:
      url: git://github.com/IOT-DSA/sdk-dslink-dart.git
      ref: 167fd865965e0116041f9d3933e87850f7c16a06
  http: ">=0.11.2 <0.12.0"
  xml: ">=2.2.3 <3.0.0"
